version: '3.4'

services:
  weatherforecast.api:
    image: ${DOCKER_REGISTRY-}weatherforecastapi
    build:
      context: .
      dockerfile: WeatherForecast.Api/Dockerfile
    ports:
      - "8081:80"
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure

  db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    ports:
      - "1433:1433"
    environment:
      MSSQL_SA_PASSWORD: "DbP@ssword!"
      ACCEPT_EULA: "Y"
    healthcheck:
      test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-Usa", "-PDbP@ssword!", "-Q", "select 1"]
      interval: 2s
      retries: 60